#https://composerize.com/
version: '3.7'

services:
    prowlarr:
      image: ghcr.io/linuxserver/prowlarr:develop
      container_name: prowlarr
      networks:
            - backend
      environment:
        - PUID
        - PGID
        - TZ=America/New_York
        - UMASK_SET=002
      volumes:
        - "${PERSISTENT_ROOT}/docker-data/prowlarr:/config"
      # ports:
      #   - 9696:9696
      restart: unless-stopped
