#https://composerize.com/
version: '3.7'

services:
    radarr:
      image: linuxserver/radarr
      container_name: radarr
      networks:
            - backend
      environment:
        - PUID
        - PGID
        - TZ=America/New_York
        - UMASK_SET=002
      volumes:
        - "${PERSISTENT_ROOT}/docker-data/radarr:/config"
        - "${PLEX_DATA}/Movies:/movies"
        - "${PLEX_DATA}/transmission:/data"
      ports:
        - 7878:7878
      restart: unless-stopped
