#https://composerize.com/
version: '3.7'

services:
    transmission:
        container_name: transmission
        command: "'dumb-init' '/etc/openvpn/start.sh'"
        networks:
            - backend
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - "${PERSISTENT_ROOT}/docker-data/transmission/scripts:/scripts"
            - "${PERSISTENT_ROOT}/docker-data/transmission/config:/config"
            - "${PLEX_DATA}/transmission:/data"
        restart: unless-stopped
        cap_add:
            - NET_ADMIN
        dns:
            - 1.1.1.1
            - 8.8.8.8
        environment:
            - OPENVPN_PASSWORD
            - OPENVPN_USERNAME
            - OPENVPN_PROVIDER
            - PUID
            - PGID
            - NORDVPN_COUNTRY
            - TRANSMISSION_BLOCKLIST_ENABLED=true
            - 'TRANSMISSION_BLOCKLIST_URL=http://john.bitsurge.net/public/biglist.p2p.gz'
            - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
            - TRANSMISSION_RPC_ENABLED=true
            - TRANSMISSION_RPC_PASSWORD
            - TRANSMISSION_RPC_PORT=9091
            - TRANSMISSION_RPC_URL=/
            - TRANSMISSION_RPC_USERNAME=ldrrp
            - TRANSMISSION_UMASK=2
            - TRANSMISSION_WATCH_DIR=/data/watch
            - TRANSMISSION_HOME=/data/transmission-home
            - HEALTH_CHECK_HOST=google.com
            - CREATE_TUN_DEVICE=true
        image: 'haugene/transmission-openvpn:latest'
