#https://composerize.com/
version: '3.7'

services:
    plex:
        container_name: plex
        volumes:
            - "${PERSISTENT_ROOT}/docker-data/plex:/config"
            - '/tmp/transcode:/transcode'
            - "${PLEX_DATA}:/data"
        restart: unless-stopped
        network_mode: host
        environment:
            - CHANGE_CONFIG_DIR_OWNERSHIP=true
            - HOME=/config
            - "PLEX_UID=${PUID}"
            - "PLEX_GID=${PGID}"
        image: 'plexinc/pms-docker:latest'
